/* Pragma */
#pragma once

/* Import */
#include "libraries/c/includes.h" // C Standard Library
#include "libraries/c++/includes.hpp" // C++ Standard Library

#include "environments/linux/includes.h" // Linux
#include "environments/windows/includes.h" // Windows

#include "shims/polyfills.hpp" // ... --- NOTE (Lapys) -> Shiv required differences between alternative implementations and versions of C++.

/* Class > ... */
struct array;
struct boolean;
struct character;
struct integral;
struct null_pointer;
struct number;
struct pointer;
struct primitive;
struct rational;
struct raw_pointer;
struct string;
struct wide;

/* Definition --- NOTE (Lapys) -> Some of these function definitions may be optimized in-definition. */
    // Array ...
    template <size_t, typename type> constexpr type* array__create(void) noexcept;

    // Number ...
    constexpr double number__absolute(double const) noexcept;
    constexpr float number__absolute(float const) noexcept;
    constexpr int number__absolute(int const) noexcept;
    long number__absolute(long const) noexcept;
    constexpr long double number__absolute(long double const) noexcept;
    constexpr short number__absolute(short const) noexcept;
    constexpr unsigned int number__absolute(unsigned int const) noexcept;
    constexpr unsigned long number__absolute(unsigned long const) noexcept;
    constexpr unsigned short number__absolute(unsigned short const) noexcept;
    wide number__absolute(wide const) noexcept;
    constexpr double number__arc_cosine(double const);
    constexpr float number__arc_cosine(float const);
    constexpr float number__arc_cosine(int const);
    constexpr double number__arc_cosine(long const);
    constexpr long double number__arc_cosine(long double const);
    constexpr float number__arc_cosine(short const);
    constexpr float number__arc_cosine(unsigned int const);
    constexpr double number__arc_cosine(unsigned long const);
    constexpr float number__arc_cosine(unsigned short const);
    long double number__arc_cosine(wide const);
    constexpr double number__arc_sine(double const);
    constexpr float number__arc_sine(float const);
    constexpr float number__arc_sine(int const);
    constexpr double number__arc_sine(long const);
    constexpr long double number__arc_sine(long double const);
    constexpr float number__arc_sine(short const);
    constexpr float number__arc_sine(unsigned int const);
    constexpr double number__arc_sine(unsigned long const);
    constexpr float number__arc_sine(unsigned short const);
    long double number__arc_sine(wide const);
    constexpr double number__arc_tangent(double const);
    constexpr float number__arc_tangent(float const);
    constexpr float number__arc_tangent(int const);
    constexpr double number__arc_tangent(long const);
    constexpr long double number__arc_tangent(long double const);
    constexpr float number__arc_tangent(short const);
    constexpr float number__arc_tangent(unsigned int const);
    constexpr double number__arc_tangent(unsigned long const);
    constexpr float number__arc_tangent(unsigned short const);
    long double number__arc_tangent(wide const);
    constexpr double number__area_hyperbolic_cosine(double const);
    constexpr float number__area_hyperbolic_cosine(float const);
    constexpr float number__area_hyperbolic_cosine(int const);
    constexpr double number__area_hyperbolic_cosine(long const);
    constexpr long double number__area_hyperbolic_cosine(long double const);
    constexpr float number__area_hyperbolic_cosine(short const);
    constexpr float number__area_hyperbolic_cosine(unsigned int const);
    constexpr double number__area_hyperbolic_cosine(unsigned long const);
    constexpr float number__area_hyperbolic_cosine(unsigned short const);
    long double number__area_hyperbolic_cosine(wide const);
    constexpr double number__area_hyperbolic_sine(double const);
    constexpr float number__area_hyperbolic_sine(float const);
    constexpr float number__area_hyperbolic_sine(int const);
    constexpr double number__area_hyperbolic_sine(long const);
    constexpr long double number__area_hyperbolic_sine(long double const);
    constexpr float number__area_hyperbolic_sine(short const);
    constexpr float number__area_hyperbolic_sine(unsigned int const);
    constexpr double number__area_hyperbolic_sine(unsigned long const);
    constexpr float number__area_hyperbolic_sine(unsigned short const);
    long double number__area_hyperbolic_sine(wide const);
    constexpr double number__area_hyperbolic_tangent(double const);
    constexpr float number__area_hyperbolic_tangent(float const);
    constexpr float number__area_hyperbolic_tangent(int const);
    constexpr double number__area_hyperbolic_tangent(long const);
    constexpr long double number__area_hyperbolic_tangent(long double const);
    constexpr float number__area_hyperbolic_tangent(short const);
    constexpr float number__area_hyperbolic_tangent(unsigned int const);
    constexpr double number__area_hyperbolic_tangent(unsigned long const);
    constexpr float number__area_hyperbolic_tangent(unsigned short const);
    long double number__area_hyperbolic_tangent(wide const);
    constexpr double number__ceiling(double const) noexcept;
    constexpr float number__ceiling(float const) noexcept;
    constexpr int number__ceiling(int const) noexcept;
    constexpr long number__ceiling(long const) noexcept;
    constexpr long double number__ceiling(long double const) noexcept;
    constexpr short number__ceiling(short const) noexcept;
    constexpr unsigned int number__ceiling(unsigned int const) noexcept;
    constexpr unsigned long number__ceiling(unsigned long const) noexcept;
    constexpr unsigned short number__ceiling(unsigned short const) noexcept;
    wide number__ceiling(wide const) noexcept;
    constexpr double number__cosine(double const);
    constexpr float number__cosine(float const);
    constexpr float number__cosine(int const);
    constexpr double number__cosine(long const);
    long double number__cosine(long double const);
    constexpr float number__cosine(short const);
    constexpr float number__cosine(unsigned int const);
    constexpr double number__cosine(unsigned long const);
    constexpr float number__cosine(unsigned short const);
    long double number__cosine(wide const);
    constexpr double number__cube_root(double const) noexcept;
    constexpr float number__cube_root(float const) noexcept;
    constexpr int number__cube_root(int const) noexcept;
    constexpr long number__cube_root(long const) noexcept;
    constexpr long double number__cube_root(long double const) noexcept;
    constexpr short number__cube_root(short const) noexcept;
    constexpr unsigned int number__cube_root(unsigned int const) noexcept;
    constexpr unsigned long number__cube_root(unsigned long const) noexcept;
    constexpr unsigned short number__cube_root(unsigned short const) noexcept;
    wide number__cube_root(wide const) noexcept;
    struct number__create_indeterminate;
    struct number__create_negative_infinity;
    struct number__create_non_computable;
    struct number__create_positive_infinity;
    constexpr long double number__exponentiate(double const, double const);
    constexpr long double number__exponentiate(double const, float const);
    constexpr long double number__exponentiate(double const, int const);
    constexpr long double number__exponentiate(double const, long const);
    constexpr long double number__exponentiate(double const, long double const);
    constexpr long double number__exponentiate(double const, short const);
    constexpr long double number__exponentiate(double const, unsigned int const);
    constexpr long double number__exponentiate(double const, unsigned long const);
    constexpr long double number__exponentiate(double const, unsigned short const);
    long double number__exponentiate(double const, wide const);
    constexpr double number__exponentiate(float const, double const);
    constexpr double number__exponentiate(float const, float const);
    constexpr double number__exponentiate(float const, int const);
    constexpr double number__exponentiate(float const, long const);
    constexpr long double number__exponentiate(float const, long double const);
    constexpr double number__exponentiate(float const, short const);
    constexpr double number__exponentiate(float const, unsigned int const);
    constexpr double number__exponentiate(float const, unsigned long const);
    constexpr double number__exponentiate(float const, unsigned short const);
    long double number__exponentiate(float const, wide const);
    constexpr long double number__exponentiate(int const, double const);
    constexpr double number__exponentiate(int const, float const);
    constexpr long number__exponentiate(int const, int const);
    constexpr wide number__exponentiate(int const, long const);
    constexpr long double number__exponentiate(int const, long double const);
    constexpr long number__exponentiate(int const, short const);
    constexpr long number__exponentiate(int const, unsigned int const);
    constexpr long number__exponentiate(int const, unsigned long const);
    constexpr long number__exponentiate(int const, unsigned short const);
    wide number__exponentiate(int const, wide const);
    constexpr long double number__exponentiate(long const, double const);
    constexpr double number__exponentiate(long const, float const);
    constexpr wide number__exponentiate(long const, int const);
    constexpr wide number__exponentiate(long const, long const);
    constexpr long double number__exponentiate(long const, long double const);
    constexpr wide number__exponentiate(long const, short const);
    constexpr wide number__exponentiate(long const, unsigned int const);
    constexpr wide number__exponentiate(long const, unsigned long const);
    constexpr wide number__exponentiate(long const, unsigned short const);
    wide number__exponentiate(long const, wide const);
    constexpr long double number__exponentiate(long double const, double const);
    constexpr long double number__exponentiate(long double const, float const);
    constexpr long double number__exponentiate(long double const, int const);
    constexpr long double number__exponentiate(long double const, long const);
    constexpr long double number__exponentiate(long double const, long double const);
    constexpr long double number__exponentiate(long double const, short const);
    constexpr long double number__exponentiate(long double const, unsigned int const);
    constexpr long double number__exponentiate(long double const, unsigned long const);
    constexpr long double number__exponentiate(long double const, unsigned short const);
    long double number__exponentiate(long double const, wide const);
    constexpr double number__exponentiate(short const, double const);
    constexpr float number__exponentiate(short const, float const);
    constexpr long number__exponentiate(short const, int const);
    constexpr long number__exponentiate(short const, long const);
    constexpr long double number__exponentiate(short const, long double const);
    constexpr int number__exponentiate(short const, short const);
    constexpr long number__exponentiate(short const, unsigned int const);
    constexpr long number__exponentiate(short const, unsigned long const);
    constexpr int number__exponentiate(short const, unsigned short const);
    int number__exponentiate(short const, wide const);
    constexpr long double number__exponentiate(unsigned int const, double const);
    constexpr double number__exponentiate(unsigned int const, float const);
    constexpr long number__exponentiate(unsigned int const, int const);
    constexpr long number__exponentiate(unsigned int const, long const);
    constexpr long double number__exponentiate(unsigned int const, long double const);
    constexpr long number__exponentiate(unsigned int const, short const);
    constexpr unsigned long number__exponentiate(unsigned int const, unsigned int const);
    constexpr unsigned long number__exponentiate(unsigned int const, unsigned long const);
    constexpr unsigned long number__exponentiate(unsigned int const, unsigned short const);
    wide number__exponentiate(unsigned int const, wide const);
    constexpr long double number__exponentiate(unsigned long const, double const);
    constexpr long double number__exponentiate(unsigned long const, float const);
    constexpr wide number__exponentiate(unsigned long const, int const);
    constexpr wide number__exponentiate(unsigned long const, long const);
    constexpr long double number__exponentiate(unsigned long const, long double const);
    constexpr wide number__exponentiate(unsigned long const, short const);
    constexpr wide number__exponentiate(unsigned long const, unsigned int const);
    constexpr wide number__exponentiate(unsigned long const, unsigned long const);
    constexpr wide number__exponentiate(unsigned long const, unsigned short const);
    wide number__exponentiate(unsigned long const, wide const);
    constexpr double number__exponentiate(unsigned short const, double const);
    constexpr double number__exponentiate(unsigned short const, float const);
    constexpr long number__exponentiate(unsigned short const, int const);
    constexpr wide number__exponentiate(unsigned short const, long const);
    constexpr long double number__exponentiate(unsigned short const, long double const);
    constexpr int number__exponentiate(unsigned short const, short const);
    constexpr unsigned long number__exponentiate(unsigned short const, unsigned int const);
    constexpr wide number__exponentiate(unsigned short const, unsigned long const);
    constexpr unsigned int number__exponentiate(unsigned short const, unsigned short const);
    wide number__exponentiate(unsigned short const, wide const);
    long double number__exponentiate(wide const, double const);
    long double number__exponentiate(wide const, float const);
    wide number__exponentiate(wide const, int const);
    wide number__exponentiate(wide const, long const);
    long double number__exponentiate(wide const, long double const);
    wide number__exponentiate(wide const, short const);
    wide number__exponentiate(wide const, unsigned int const);
    wide number__exponentiate(wide const, unsigned long const);
    wide number__exponentiate(wide const, unsigned short const);
    wide number__exponentiate(wide const, wide const);
    constexpr double number__exponentiate_eulers_number(double const);
    constexpr float number__exponentiate_eulers_number(float const);
    constexpr float number__exponentiate_eulers_number(int const);
    long double number__exponentiate_eulers_number(long const);
    long double number__exponentiate_eulers_number(long double const);
    constexpr float number__exponentiate_eulers_number(short const);
    constexpr float number__exponentiate_eulers_number(unsigned int const);
    long double number__exponentiate_eulers_number(unsigned long const);
    constexpr float number__exponentiate_eulers_number(unsigned short const);
    long double number__exponentiate_eulers_number(wide const);
    double number__floor(double const) noexcept;
    float number__floor(float const) noexcept;
    constexpr int number__floor(int const) noexcept;
    constexpr long number__floor(long const) noexcept;
    long double number__floor(long double const) noexcept;
    constexpr short number__floor(short const) noexcept;
    constexpr unsigned int number__floor(unsigned int const) noexcept;
    constexpr unsigned long number__floor(unsigned long const) noexcept;
    constexpr unsigned short number__floor(unsigned short const) noexcept;
    constexpr wide number__floor(wide const) noexcept;
    constexpr double number__hyperbolic_cosine(double const);
    constexpr float number__hyperbolic_cosine(float const);
    constexpr float number__hyperbolic_cosine(int const);
    constexpr double number__hyperbolic_cosine(long const);
    long double number__hyperbolic_cosine(long double const);
    constexpr float number__hyperbolic_cosine(short const);
    constexpr float number__hyperbolic_cosine(unsigned int const);
    constexpr double number__hyperbolic_cosine(unsigned long const);
    constexpr float number__hyperbolic_cosine(unsigned short const);
    long double number__hyperbolic_cosine(wide const);
    constexpr double number__hyperbolic_sine(double const);
    constexpr float number__hyperbolic_sine(float const);
    constexpr float number__hyperbolic_sine(int const);
    constexpr double number__hyperbolic_sine(long const);
    long double number__hyperbolic_sine(long double const);
    constexpr float number__hyperbolic_sine(short const);
    constexpr float number__hyperbolic_sine(unsigned int const);
    constexpr double number__hyperbolic_sine(unsigned long const);
    constexpr float number__hyperbolic_sine(unsigned short const);
    long double number__hyperbolic_sine(wide const);
    constexpr double number__hyperbolic_tangent(double const);
    constexpr float number__hyperbolic_tangent(float const);
    constexpr float number__hyperbolic_tangent(int const);
    constexpr double number__hyperbolic_tangent(long const);
    long double number__hyperbolic_tangent(long double const);
    constexpr float number__hyperbolic_tangent(short const);
    constexpr float number__hyperbolic_tangent(unsigned int const);
    constexpr double number__hyperbolic_tangent(unsigned long const);
    constexpr float number__hyperbolic_tangent(unsigned short const);
    long double number__hyperbolic_tangent(wide const);
    bool number__is_approximate_zero(double const, double const tolerance = DBL_EPSILON) noexcept;
    bool number__is_approximate_zero(double const, float const tolerance = FLT_EPSILON) noexcept;
    bool number__is_approximate_zero(double const, int const tolerance = INT_EPSILON) noexcept;
    bool number__is_approximate_zero(double const, long const tolerance = LONG_EPSILON) noexcept;
    bool number__is_approximate_zero(double const, long double const tolerance = LDBL_EPSILON) noexcept;
    bool number__is_approximate_zero(double const, short const tolerance = SHRT_EPSILON) noexcept;
    bool number__is_approximate_zero(double const, unsigned int const tolerance = UINT_EPSILON) noexcept;
    bool number__is_approximate_zero(double const, unsigned long const tolerance = ULONG_EPSILON) noexcept;
    bool number__is_approximate_zero(double const, unsigned short const tolerance = USHRT_EPSILON) noexcept;
    bool number__is_approximate_zero(double const, wide const tolerance = LLONG_EPSILON) noexcept;
    bool number__is_approximate_zero(float const, double const tolerance = DBL_EPSILON) noexcept;
    bool number__is_approximate_zero(float const, float const tolerance = FLT_EPSILON) noexcept;
    bool number__is_approximate_zero(float const, int const tolerance = INT_EPSILON) noexcept;
    bool number__is_approximate_zero(float const, long const tolerance = LONG_EPSILON) noexcept;
    bool number__is_approximate_zero(float const, long double const tolerance = LDBL_EPSILON) noexcept;
    bool number__is_approximate_zero(float const, short const tolerance = SHRT_EPSILON) noexcept;
    bool number__is_approximate_zero(float const, unsigned int const tolerance = UINT_EPSILON) noexcept;
    bool number__is_approximate_zero(float const, unsigned long const tolerance = ULONG_EPSILON) noexcept;
    bool number__is_approximate_zero(float const, unsigned short const tolerance = USHRT_EPSILON) noexcept;
    bool number__is_approximate_zero(float const, wide const tolerance = LLONG_EPSILON) noexcept;
    constexpr bool number__is_approximate_zero(int const, double const = DBL_EPSILON) noexcept;
    constexpr bool number__is_approximate_zero(int const, float const = FLT_EPSILON) noexcept;
    constexpr bool number__is_approximate_zero(int const, int const = INT_EPSILON) noexcept;
    constexpr bool number__is_approximate_zero(int const, long const = LONG_EPSILON) noexcept;
    constexpr bool number__is_approximate_zero(int const, long double const = LDBL_EPSILON) noexcept;
    constexpr bool number__is_approximate_zero(int const, short const = SHRT_EPSILON) noexcept;
    constexpr bool number__is_approximate_zero(int const, unsigned int const = UINT_EPSILON) noexcept;
    constexpr bool number__is_approximate_zero(int const, unsigned long const = ULONG_EPSILON) noexcept;
    constexpr bool number__is_approximate_zero(int const, unsigned short const = USHRT_EPSILON) noexcept;
    constexpr bool number__is_approximate_zero(int const, wide const = LLONG_EPSILON) noexcept;
    constexpr bool number__is_approximate_zero(long const, double const = DBL_EPSILON) noexcept;
    constexpr bool number__is_approximate_zero(long const, float const = FLT_EPSILON) noexcept;
    constexpr bool number__is_approximate_zero(long const, int const = INT_EPSILON) noexcept;
    constexpr bool number__is_approximate_zero(long const, long const = LONG_EPSILON) noexcept;
    constexpr bool number__is_approximate_zero(long const, long double const = LDBL_EPSILON) noexcept;
    constexpr bool number__is_approximate_zero(long const, short const = SHRT_EPSILON) noexcept;
    constexpr bool number__is_approximate_zero(long const, unsigned int const = UINT_EPSILON) noexcept;
    constexpr bool number__is_approximate_zero(long const, unsigned long const = ULONG_EPSILON) noexcept;
    constexpr bool number__is_approximate_zero(long const, unsigned short const = USHRT_EPSILON) noexcept;
    constexpr bool number__is_approximate_zero(long const, wide const = LLONG_EPSILON) noexcept;
    bool number__is_approximate_zero(long double const, double const tolerance = DBL_EPSILON) noexcept;
    bool number__is_approximate_zero(long double const, float const tolerance = FLT_EPSILON) noexcept;
    bool number__is_approximate_zero(long double const, int const tolerance = INT_EPSILON) noexcept;
    bool number__is_approximate_zero(long double const, long const tolerance = LONG_EPSILON) noexcept;
    bool number__is_approximate_zero(long double const, long double const tolerance = LDBL_EPSILON) noexcept;
    bool number__is_approximate_zero(long double const, short const tolerance = SHRT_EPSILON) noexcept;
    bool number__is_approximate_zero(long double const, unsigned int const tolerance = UINT_EPSILON) noexcept;
    bool number__is_approximate_zero(long double const, unsigned long const tolerance = ULONG_EPSILON) noexcept;
    bool number__is_approximate_zero(long double const, unsigned short const tolerance = USHRT_EPSILON) noexcept;
    bool number__is_approximate_zero(long double const, wide const tolerance = LLONG_EPSILON) noexcept;
    constexpr bool number__is_approximate_zero(short const, double const = DBL_EPSILON) noexcept;
    constexpr bool number__is_approximate_zero(short const, float const = FLT_EPSILON) noexcept;
    constexpr bool number__is_approximate_zero(short const, int const = INT_EPSILON) noexcept;
    constexpr bool number__is_approximate_zero(short const, long const = LONG_EPSILON) noexcept;
    constexpr bool number__is_approximate_zero(short const, long double const = LDBL_EPSILON) noexcept;
    constexpr bool number__is_approximate_zero(short const, short const = SHRT_EPSILON) noexcept;
    constexpr bool number__is_approximate_zero(short const, unsigned int const = UINT_EPSILON) noexcept;
    constexpr bool number__is_approximate_zero(short const, unsigned long const = ULONG_EPSILON) noexcept;
    constexpr bool number__is_approximate_zero(short const, unsigned short const = USHRT_EPSILON) noexcept;
    constexpr bool number__is_approximate_zero(short const, wide const = LLONG_EPSILON) noexcept;
    constexpr bool number__is_approximate_zero(unsigned int const, double const = DBL_EPSILON) noexcept;
    constexpr bool number__is_approximate_zero(unsigned int const, float const = FLT_EPSILON) noexcept;
    constexpr bool number__is_approximate_zero(unsigned int const, int const = INT_EPSILON) noexcept;
    constexpr bool number__is_approximate_zero(unsigned int const, long const = LONG_EPSILON) noexcept;
    constexpr bool number__is_approximate_zero(unsigned int const, long double const = LDBL_EPSILON) noexcept;
    constexpr bool number__is_approximate_zero(unsigned int const, short const = SHRT_EPSILON) noexcept;
    constexpr bool number__is_approximate_zero(unsigned int const, unsigned int const = UINT_EPSILON) noexcept;
    constexpr bool number__is_approximate_zero(unsigned int const, unsigned long const = ULONG_EPSILON) noexcept;
    constexpr bool number__is_approximate_zero(unsigned int const, unsigned short const = USHRT_EPSILON) noexcept;
    constexpr bool number__is_approximate_zero(unsigned int const, wide const = ULLONG_EPSILON) noexcept;
    constexpr bool number__is_approximate_zero(unsigned long const, double const = DBL_EPSILON) noexcept;
    constexpr bool number__is_approximate_zero(unsigned long const, float const = FLT_EPSILON) noexcept;
    constexpr bool number__is_approximate_zero(unsigned long const, int const = INT_EPSILON) noexcept;
    constexpr bool number__is_approximate_zero(unsigned long const, long const = LONG_EPSILON) noexcept;
    constexpr bool number__is_approximate_zero(unsigned long const, long double const = LDBL_EPSILON) noexcept;
    constexpr bool number__is_approximate_zero(unsigned long const, short const = SHRT_EPSILON) noexcept;
    constexpr bool number__is_approximate_zero(unsigned long const, unsigned int const = UINT_EPSILON) noexcept;
    constexpr bool number__is_approximate_zero(unsigned long const, unsigned long const = ULONG_EPSILON) noexcept;
    constexpr bool number__is_approximate_zero(unsigned long const, unsigned short const = USHRT_EPSILON) noexcept;
    constexpr bool number__is_approximate_zero(unsigned long const, wide const = ULLONG_EPSILON) noexcept;
    constexpr bool number__is_approximate_zero(unsigned short const, double const = DBL_EPSILON) noexcept;
    constexpr bool number__is_approximate_zero(unsigned short const, float const = FLT_EPSILON) noexcept;
    constexpr bool number__is_approximate_zero(unsigned short const, int const = INT_EPSILON) noexcept;
    constexpr bool number__is_approximate_zero(unsigned short const, long const = LONG_EPSILON) noexcept;
    constexpr bool number__is_approximate_zero(unsigned short const, long double const = LDBL_EPSILON) noexcept;
    constexpr bool number__is_approximate_zero(unsigned short const, short const = SHRT_EPSILON) noexcept;
    constexpr bool number__is_approximate_zero(unsigned short const, unsigned int const = UINT_EPSILON) noexcept;
    constexpr bool number__is_approximate_zero(unsigned short const, unsigned long const = ULONG_EPSILON) noexcept;
    constexpr bool number__is_approximate_zero(unsigned short const, unsigned short const = USHRT_EPSILON) noexcept;
    constexpr bool number__is_approximate_zero(unsigned short const, wide const = USHRT_EPSILON) noexcept;
    bool number__is_approximate_zero(wide const, double const = DBL_EPSILON) noexcept;
    bool number__is_approximate_zero(wide const, float const = FLT_EPSILON) noexcept;
    bool number__is_approximate_zero(wide const, int const = INT_EPSILON) noexcept;
    bool number__is_approximate_zero(wide const, long const = LONG_EPSILON) noexcept;
    bool number__is_approximate_zero(wide const, long double const = LDBL_EPSILON) noexcept;
    bool number__is_approximate_zero(wide const, short const = SHRT_EPSILON) noexcept;
    bool number__is_approximate_zero(wide const, unsigned int const = UINT_EPSILON) noexcept;
    bool number__is_approximate_zero(wide const, unsigned long const = ULONG_EPSILON) noexcept;
    bool number__is_approximate_zero(wide const, unsigned short const = USHRT_EPSILON) noexcept;
    bool number__is_approximate_zero(wide const, wide const = ULLONG_EPSILON) noexcept;
    constexpr bool number__is_computable(double const) noexcept;
    constexpr bool number__is_computable(float const) noexcept;
    constexpr bool number__is_computable(int const) noexcept;
    constexpr bool number__is_computable(long const) noexcept;
    constexpr bool number__is_computable(long double const) noexcept;
    constexpr bool number__is_computable(short const) noexcept;
    constexpr bool number__is_computable(unsigned int const) noexcept;
    constexpr bool number__is_computable(unsigned long const) noexcept;
    constexpr bool number__is_computable(unsigned short const) noexcept;
    constexpr bool number__is_computable(wide const) noexcept;
    bool number__is_determinate(double const) noexcept;
    bool number__is_determinate(float const) noexcept;
    constexpr bool number__is_determinate(int const) noexcept;
    constexpr bool number__is_determinate(long const) noexcept;
    bool number__is_determinate(long double const) noexcept;
    constexpr bool number__is_determinate(short const) noexcept;
    constexpr bool number__is_determinate(unsigned int const) noexcept;
    constexpr bool number__is_determinate(unsigned long const) noexcept;
    constexpr bool number__is_determinate(unsigned short const) noexcept;
    constexpr bool number__is_determinate(wide const) noexcept;
    bool number__is_finite(double const) noexcept;
    bool number__is_finite(float const) noexcept;
    constexpr bool number__is_finite(int const) noexcept;
    constexpr bool number__is_finite(long const) noexcept;
    bool number__is_finite(long double const) noexcept;
    constexpr bool number__is_finite(short const) noexcept;
    constexpr bool number__is_finite(unsigned int const) noexcept;
    constexpr bool number__is_finite(unsigned long const) noexcept;
    constexpr bool number__is_finite(unsigned short const) noexcept;
    constexpr bool number__is_finite(wide const) noexcept;
    constexpr bool number__is_infinite(double const) noexcept;
    constexpr bool number__is_infinite(float const) noexcept;
    constexpr bool number__is_infinite(int const) noexcept;
    constexpr bool number__is_infinite(long const) noexcept;
    constexpr bool number__is_infinite(long double const) noexcept;
    constexpr bool number__is_infinite(short const) noexcept;
    constexpr bool number__is_infinite(unsigned int const) noexcept;
    constexpr bool number__is_infinite(unsigned long const) noexcept;
    constexpr bool number__is_infinite(unsigned short const) noexcept;
    constexpr bool number__is_infinite(wide const) noexcept;
    bool number__is_normalized(double const) noexcept;
    bool number__is_normalized(float const) noexcept;
    constexpr bool number__is_normalized(int const) noexcept;
    constexpr bool number__is_normalized(long const) noexcept;
    bool number__is_normalized(long double const) noexcept;
    constexpr bool number__is_normalized(short const) noexcept;
    constexpr bool number__is_normalized(unsigned int const) noexcept;
    constexpr bool number__is_normalized(unsigned long const) noexcept;
    constexpr bool number__is_normalized(unsigned short const) noexcept;
    constexpr bool number__is_normalized(wide const) noexcept;
    bool number__is_safe(double const) noexcept;
    bool number__is_safe(float const) noexcept;
    bool number__is_safe(int const) noexcept;
    bool number__is_safe(long const) noexcept;
    bool number__is_safe(long double const) noexcept;
    bool number__is_safe(short const) noexcept;
    bool number__is_safe(unsigned int const) noexcept;
    bool number__is_safe(unsigned long const) noexcept;
    bool number__is_safe(unsigned short const) noexcept;
    bool number__is_safe(wide const) noexcept;
    constexpr double number__logarithm(double const);
    constexpr float number__logarithm(float const);
    constexpr float number__logarithm(int const);
    constexpr double number__logarithm(long const);
    constexpr long double number__logarithm(long double const);
    constexpr float number__logarithm(short const);
    constexpr float number__logarithm(unsigned int const);
    constexpr double number__logarithm(unsigned long const);
    constexpr float number__logarithm(unsigned short const);
    long double number__logarithm(wide const);
    constexpr double number__maximum(double const, double const) noexcept;
    constexpr double number__maximum(double const, float const) noexcept;
    constexpr double number__maximum(double const, int const) noexcept;
    constexpr double number__maximum(double const, long const) noexcept;
    constexpr long double number__maximum(double const, long double const) noexcept;
    constexpr double number__maximum(double const, short const) noexcept;
    constexpr double number__maximum(double const, unsigned int const) noexcept;
    constexpr double number__maximum(double const, unsigned long const) noexcept;
    constexpr double number__maximum(double const, unsigned short const) noexcept;
    long double number__maximum(double const, wide const) noexcept;
    constexpr double number__maximum(float const, double const) noexcept;
    constexpr float number__maximum(float const, float const) noexcept;
    constexpr float number__maximum(float const, int const) noexcept;
    constexpr double number__maximum(float const, long const) noexcept;
    constexpr long double number__maximum(float const, long double const) noexcept;
    constexpr float number__maximum(float const, short const) noexcept;
    constexpr float number__maximum(float const, unsigned int const) noexcept;
    constexpr double number__maximum(float const, unsigned long const) noexcept;
    constexpr double number__maximum(float const, unsigned short const) noexcept;
    long double number__maximum(float const, wide const) noexcept;
    constexpr double number__maximum(int const, double const) noexcept;
    constexpr float number__maximum(int const, float const) noexcept;
    constexpr int number__maximum(int const, int const) noexcept;
    constexpr long number__maximum(int const, long const) noexcept;
    constexpr long double number__maximum(int const, long double const) noexcept;
    constexpr int number__maximum(int const, short const) noexcept;
    constexpr long number__maximum(int const, unsigned int const) noexcept;
    constexpr double number__maximum(int const, unsigned long const) noexcept;
    constexpr long number__maximum(int const, unsigned short const) noexcept;
    wide number__maximum(int const, wide const) noexcept;
    constexpr double number__maximum(long const, double const) noexcept;
    constexpr double number__maximum(long const, float const) noexcept;
    constexpr long number__maximum(long const, int const) noexcept;
    constexpr long number__maximum(long const, long const) noexcept;
    constexpr long double number__maximum(long const, long double const) noexcept;
    constexpr long number__maximum(long const, short const) noexcept;
    constexpr double number__maximum(long const, unsigned int const) noexcept;
    constexpr double number__maximum(long const, unsigned long const) noexcept;
    constexpr double number__maximum(long const, unsigned short const) noexcept;
    long double number__maximum(long const, wide const) noexcept;
    constexpr long double number__maximum(long double const, double const) noexcept;
    constexpr long double number__maximum(long double const, float const) noexcept;
    constexpr long double number__maximum(long double const, int const) noexcept;
    constexpr long double number__maximum(long double const, long const) noexcept;
    constexpr long double number__maximum(long double const, long double const) noexcept;
    constexpr long double number__maximum(long double const, short const) noexcept;
    constexpr long double number__maximum(long double const, unsigned int const) noexcept;
    constexpr long double number__maximum(long double const, unsigned long const) noexcept;
    constexpr long double number__maximum(long double const, unsigned short const) noexcept;
    long double number__maximum(long double const, wide const) noexcept;
    constexpr double number__maximum(short const, double const) noexcept;
    constexpr float number__maximum(short const, float const) noexcept;
    constexpr int number__maximum(short const, int const) noexcept;
    constexpr long number__maximum(short const, long const) noexcept;
    constexpr long double number__maximum(short const, long double const) noexcept;
    constexpr short number__maximum(short const, short const) noexcept;
    constexpr long number__maximum(short const, unsigned int const) noexcept;
    constexpr double number__maximum(short const, unsigned long const) noexcept;
    constexpr int number__maximum(short const, unsigned short const) noexcept;
    long double number__maximum(short const, wide const) noexcept;
    constexpr double number__maximum(unsigned int const, double const) noexcept;
    constexpr float number__maximum(unsigned int const, float const) noexcept;
    constexpr long number__maximum(unsigned int const, int const) noexcept;
    constexpr long number__maximum(unsigned int const, long const) noexcept;
    constexpr long double number__maximum(unsigned int const, long double const) noexcept;
    constexpr long number__maximum(unsigned int const, short const) noexcept;
    constexpr unsigned int number__maximum(unsigned int const, unsigned int const) noexcept;
    constexpr unsigned long number__maximum(unsigned int const, unsigned long const) noexcept;
    constexpr unsigned int number__maximum(unsigned int const, unsigned short const) noexcept;
    wide number__maximum(unsigned int const, wide const) noexcept;
    constexpr double number__maximum(unsigned long const, double const) noexcept;
    constexpr float number__maximum(unsigned long const, float const) noexcept;
    constexpr double number__maximum(unsigned long const, int const) noexcept;
    constexpr double number__maximum(unsigned long const, long const) noexcept;
    constexpr long double number__maximum(unsigned long const, long double const) noexcept;
    constexpr double number__maximum(unsigned long const, short const) noexcept;
    constexpr double number__maximum(unsigned long const, unsigned int const) noexcept;
    constexpr unsigned long number__maximum(unsigned long const, unsigned long const) noexcept;
    constexpr unsigned long number__maximum(unsigned long const, unsigned short const) noexcept;
    wide number__maximum(unsigned long const, wide const) noexcept;
    constexpr double number__maximum(unsigned short const, double const) noexcept;
    constexpr float number__maximum(unsigned short const, float const) noexcept;
    constexpr long number__maximum(unsigned short const, int const) noexcept;
    constexpr long number__maximum(unsigned short const, long const) noexcept;
    constexpr long double number__maximum(unsigned short const, long double const) noexcept;
    constexpr int number__maximum(unsigned short const, short const) noexcept;
    constexpr unsigned int number__maximum(unsigned short const, unsigned int const) noexcept;
    constexpr unsigned long number__maximum(unsigned short const, unsigned long const) noexcept;
    constexpr unsigned short number__maximum(unsigned short const, unsigned short const) noexcept;
    wide number__maximum(unsigned short const, wide const) noexcept;
    long double number__maximum(wide const, double const) noexcept;
    long double number__maximum(wide const, float const) noexcept;
    wide number__maximum(wide const, int const) noexcept;
    wide number__maximum(wide const, long const) noexcept;
    long double number__maximum(wide const, long double const) noexcept;
    wide number__maximum(wide const, short const) noexcept;
    wide number__maximum(wide const, unsigned int const) noexcept;
    wide number__maximum(wide const, unsigned long const) noexcept;
    wide number__maximum(wide const, unsigned short const) noexcept;
    wide number__maximum(wide const, wide const) noexcept;
    constexpr double number__minimum(double const, double const) noexcept;
    constexpr double number__minimum(double const, float const) noexcept;
    constexpr double number__minimum(double const, int const) noexcept;
    constexpr double number__minimum(double const, long const) noexcept;
    constexpr long double number__minimum(double const, long double const) noexcept;
    constexpr double number__minimum(double const, short const) noexcept;
    constexpr double number__minimum(double const, unsigned int const) noexcept;
    constexpr double number__minimum(double const, unsigned long const) noexcept;
    constexpr double number__minimum(double const, unsigned short const) noexcept;
    long double number__minimum(double const, wide const) noexcept;
    constexpr double number__minimum(float const, double const) noexcept;
    constexpr float number__minimum(float const, float const) noexcept;
    constexpr float number__minimum(float const, int const) noexcept;
    constexpr double number__minimum(float const, long const) noexcept;
    constexpr long double number__minimum(float const, long double const) noexcept;
    constexpr float number__minimum(float const, short const) noexcept;
    constexpr float number__minimum(float const, unsigned int const) noexcept;
    constexpr double number__minimum(float const, unsigned long const) noexcept;
    constexpr double number__minimum(float const, unsigned short const) noexcept;
    long double number__minimum(float const, wide const) noexcept;
    constexpr double number__minimum(int const, double const) noexcept;
    constexpr float number__minimum(int const, float const) noexcept;
    constexpr int number__minimum(int const, int const) noexcept;
    constexpr long number__minimum(int const, long const) noexcept;
    constexpr long double number__minimum(int const, long double const) noexcept;
    constexpr int number__minimum(int const, short const) noexcept;
    constexpr long number__minimum(int const, unsigned int const) noexcept;
    constexpr double number__minimum(int const, unsigned long const) noexcept;
    constexpr long number__minimum(int const, unsigned short const) noexcept;
    wide number__minimum(int const, wide const) noexcept;
    constexpr double number__minimum(long const, double const) noexcept;
    constexpr double number__minimum(long const, float const) noexcept;
    constexpr long number__minimum(long const, int const) noexcept;
    constexpr long number__minimum(long const, long const) noexcept;
    constexpr long double number__minimum(long const, long double const) noexcept;
    constexpr long number__minimum(long const, short const) noexcept;
    constexpr double number__minimum(long const, unsigned int const) noexcept;
    constexpr double number__minimum(long const, unsigned long const) noexcept;
    constexpr double number__minimum(long const, unsigned short const) noexcept;
    long double number__minimum(long const, wide const) noexcept;
    constexpr long double number__minimum(long double const, double const) noexcept;
    constexpr long double number__minimum(long double const, float const) noexcept;
    constexpr long double number__minimum(long double const, int const) noexcept;
    constexpr long double number__minimum(long double const, long const) noexcept;
    constexpr long double number__minimum(long double const, long double const) noexcept;
    constexpr long double number__minimum(long double const, short const) noexcept;
    constexpr long double number__minimum(long double const, unsigned int const) noexcept;
    constexpr long double number__minimum(long double const, unsigned long const) noexcept;
    constexpr long double number__minimum(long double const, unsigned short const) noexcept;
    long double number__minimum(long double const, wide const) noexcept;
    constexpr double number__minimum(short const, double const) noexcept;
    constexpr float number__minimum(short const, float const) noexcept;
    constexpr int number__minimum(short const, int const) noexcept;
    constexpr long number__minimum(short const, long const) noexcept;
    constexpr long double number__minimum(short const, long double const) noexcept;
    constexpr short number__minimum(short const, short const) noexcept;
    constexpr long number__minimum(short const, unsigned int const) noexcept;
    constexpr double number__minimum(short const, unsigned long const) noexcept;
    constexpr int number__minimum(short const, unsigned short const) noexcept;
    long double number__minimum(short const, wide const) noexcept;
    constexpr double number__minimum(unsigned int const, double const) noexcept;
    constexpr float number__minimum(unsigned int const, float const) noexcept;
    constexpr long number__minimum(unsigned int const, int const) noexcept;
    constexpr long number__minimum(unsigned int const, long const) noexcept;
    constexpr long double number__minimum(unsigned int const, long double const) noexcept;
    constexpr long number__minimum(unsigned int const, short const) noexcept;
    constexpr unsigned int number__minimum(unsigned int const, unsigned int const) noexcept;
    constexpr unsigned long number__minimum(unsigned int const, unsigned long const) noexcept;
    constexpr unsigned int number__minimum(unsigned int const, unsigned short const) noexcept;
    wide number__minimum(unsigned int const, wide const) noexcept;
    constexpr double number__minimum(unsigned long const, double const) noexcept;
    constexpr float number__minimum(unsigned long const, float const) noexcept;
    constexpr double number__minimum(unsigned long const, int const) noexcept;
    constexpr double number__minimum(unsigned long const, long const) noexcept;
    constexpr long double number__minimum(unsigned long const, long double const) noexcept;
    constexpr double number__minimum(unsigned long const, short const) noexcept;
    constexpr double number__minimum(unsigned long const, unsigned int const) noexcept;
    constexpr unsigned long number__minimum(unsigned long const, unsigned long const) noexcept;
    constexpr unsigned long number__minimum(unsigned long const, unsigned short const) noexcept;
    wide number__minimum(unsigned long const, wide const) noexcept;
    constexpr double number__minimum(unsigned short const, double const) noexcept;
    constexpr float number__minimum(unsigned short const, float const) noexcept;
    constexpr long number__minimum(unsigned short const, int const) noexcept;
    constexpr long number__minimum(unsigned short const, long const) noexcept;
    constexpr long double number__minimum(unsigned short const, long double const) noexcept;
    constexpr int number__minimum(unsigned short const, short const) noexcept;
    constexpr unsigned int number__minimum(unsigned short const, unsigned int const) noexcept;
    constexpr unsigned long number__minimum(unsigned short const, unsigned long const) noexcept;
    constexpr unsigned short number__minimum(unsigned short const, unsigned short const) noexcept;
    wide number__minimum(unsigned short const, wide const) noexcept;
    long double number__minimum(wide const, double const) noexcept;
    long double number__minimum(wide const, float const) noexcept;
    wide number__minimum(wide const, int const) noexcept;
    wide number__minimum(wide const, long const) noexcept;
    long double number__minimum(wide const, long double const) noexcept;
    wide number__minimum(wide const, short const) noexcept;
    wide number__minimum(wide const, unsigned int const) noexcept;
    wide number__minimum(wide const, unsigned long const) noexcept;
    wide number__minimum(wide const, unsigned short const) noexcept;
    wide number__minimum(wide const, wide const) noexcept;
    int number__random(void) noexcept;
    long double number__root(double const, double const);
    long double number__root(double const, float const);
    double number__root(double const, int const);
    double number__root(double const, long const);
    long double number__root(double const, long double const);
    double number__root(double const, short const);
    double number__root(double const, unsigned int const);
    double number__root(double const, unsigned long const);
    double number__root(double const, unsigned short const);
    double number__root(double const, wide const);
    double number__root(float const, double const);
    double number__root(float const, float const);
    float number__root(float const, int const);
    float number__root(float const, long const);
    long double number__root(float const, long double const);
    float number__root(float const, short const);
    float number__root(float const, unsigned int const);
    float number__root(float const, unsigned long const);
    float number__root(float const, unsigned short const);
    float number__root(float const, wide const);
    long double number__root(int const, double const);
    double number__root(int const, float const);
    int number__root(int const, int const);
    int number__root(int const, long const);
    long double number__root(int const, long double const);
    int number__root(int const, short const);
    int number__root(int const, unsigned int const);
    int number__root(int const, unsigned long const);
    int number__root(int const, unsigned short const);
    int number__root(int const, wide const);
    long double number__root(long const, double const);
    double number__root(long const, float const);
    long number__root(long const, int const);
    long number__root(long const, long const);
    long double number__root(long const, long double const);
    long number__root(long const, short const);
    long number__root(long const, unsigned int const);
    long number__root(long const, unsigned long const);
    long number__root(long const, unsigned short const);
    long number__root(long const, wide const);
    long double number__root(long double const, double const);
    long double number__root(long double const, float const);
    long double number__root(long double const, int const);
    long double number__root(long double const, long const);
    long double number__root(long double const, long double const);
    long double number__root(long double const, short const);
    long double number__root(long double const, unsigned int const);
    long double number__root(long double const, unsigned long const);
    long double number__root(long double const, unsigned short const);
    long double number__root(long double const, wide const);
    double number__root(short const, double const);
    float number__root(short const, float const);
    short number__root(short const, int const);
    short number__root(short const, long const);
    long double number__root(short const, long double const);
    short number__root(short const, short const);
    short number__root(short const, unsigned int const);
    short number__root(short const, unsigned long const);
    short number__root(short const, unsigned short const);
    short number__root(short const, wide const);
    long double number__root(unsigned int const, double const);
    double number__root(unsigned int const, float const);
    int number__root(unsigned int const, int const);
    int number__root(unsigned int const, long const);
    long double number__root(unsigned int const, long double const);
    long number__root(unsigned int const, short const);
    unsigned int number__root(unsigned int const, unsigned int const);
    unsigned int number__root(unsigned int const, unsigned long const);
    unsigned int number__root(unsigned int const, unsigned short const);
    unsigned int number__root(unsigned int const, wide const);
    long double number__root(unsigned long const, double const);
    long double number__root(unsigned long const, float const);
    unsigned long number__root(unsigned long const, int const);
    unsigned long number__root(unsigned long const, long const);
    long double number__root(unsigned long const, long double const);
    unsigned long number__root(unsigned long const, short const);
    unsigned long number__root(unsigned long const, unsigned int const);
    unsigned long number__root(unsigned long const, unsigned long const);
    unsigned long number__root(unsigned long const, unsigned short const);
    unsigned long number__root(unsigned long const, wide const);
    double number__root(unsigned short const, double const);
    double number__root(unsigned short const, float const);
    unsigned short number__root(unsigned short const, int const);
    unsigned short number__root(unsigned short const, long const);
    long double number__root(unsigned short const, long double const);
    unsigned short number__root(unsigned short const, short const);
    unsigned short number__root(unsigned short const, unsigned int const);
    unsigned short number__root(unsigned short const, unsigned long const);
    unsigned short number__root(unsigned short const, unsigned short const);
    unsigned short number__root(unsigned short const, wide const);
    long double number__root(wide const, double const);
    long double number__root(wide const, float const);
    wide number__root(wide const, int const);
    wide number__root(wide const, long const);
    long double number__root(wide const, long double const);
    wide number__root(wide const, short const);
    wide number__root(wide const, unsigned int const);
    wide number__root(wide const, unsigned long const);
    wide number__root(wide const, unsigned short const);
    wide number__root(wide const, wide const);
    constexpr double number__round(double const) noexcept;
    constexpr float number__round(float const) noexcept;
    constexpr int number__round(int const) noexcept;
    constexpr long number__round(long const) noexcept;
    constexpr long double number__round(long double const) noexcept;
    constexpr short number__round(short const) noexcept;
    constexpr unsigned int number__round(unsigned int const) noexcept;
    constexpr unsigned long number__round(unsigned long const) noexcept;
    constexpr unsigned short number__round(unsigned short const) noexcept;
    wide number__round(wide const number) noexcept;
    constexpr double number__sine(double const);
    constexpr float number__sine(float const);
    constexpr float number__sine(int const);
    constexpr double number__sine(long const);
    long double number__sine(long double const);
    constexpr float number__sine(short const);
    constexpr float number__sine(unsigned int const);
    constexpr double number__sine(unsigned long const);
    constexpr float number__sine(unsigned short const);
    long double number__sine(wide const);
    constexpr double number__square_root(double const) noexcept;
    constexpr float number__square_root(float const) noexcept;
    constexpr int number__square_root(int const) noexcept;
    constexpr long number__square_root(long const) noexcept;
    constexpr long double number__square_root(long double const) noexcept;
    constexpr short number__square_root(short const) noexcept;
    constexpr unsigned int number__square_root(unsigned int const) noexcept;
    constexpr unsigned long number__square_root(unsigned long const) noexcept;
    constexpr unsigned short number__square_root(unsigned short const) noexcept;
    wide number__square_root(wide const) noexcept;
    constexpr double number__tangent(double const);
    constexpr float number__tangent(float const);
    constexpr float number__tangent(int const);
    constexpr double number__tangent(long const);
    long double number__tangent(long double const);
    constexpr float number__tangent(short const);
    constexpr float number__tangent(unsigned int const);
    constexpr double number__tangent(unsigned long const);
    constexpr float number__tangent(unsigned short const);
    long double number__tangent(wide const);
    double number__to_integer(double const) noexcept;
    float number__to_integer(float const) noexcept;
    int number__to_integer(int const) noexcept;
    long number__to_integer(long const) noexcept;
    long double number__to_integer(long double const) noexcept;
    short number__to_integer(short const) noexcept;
    unsigned int number__to_integer(unsigned int const) noexcept;
    unsigned long number__to_integer(unsigned long const) noexcept;
    unsigned short number__to_integer(unsigned short const) noexcept;
    wide number__to_integer(wide const) noexcept;
    double number__to_mantissa(double const) noexcept;
    float number__to_mantissa(float const) noexcept;
    int number__to_mantissa(int const) noexcept;
    long number__to_mantissa(long const) noexcept;
    long double number__to_mantissa(long double const) noexcept;
    short number__to_mantissa(short const) noexcept;
    unsigned int number__to_mantissa(unsigned int const) noexcept;
    unsigned long number__to_mantissa(unsigned long const) noexcept;
    unsigned short number__to_mantissa(unsigned short const) noexcept;
    wide number__to_mantissa(wide const) noexcept;
    char const* number__to_string(double const) noexcept;
    char const* number__to_string(float const) noexcept;
    char const* number__to_string(int const) noexcept;
    char const* number__to_string(long const) noexcept;
    char const* number__to_string(long double const) noexcept;
    char const* number__to_string(short const) noexcept;
    char const* number__to_string(unsigned int const) noexcept;
    char const* number__to_string(unsigned long const) noexcept;
    char const* number__to_string(unsigned short const) noexcept;
    char const* number__to_string(wide const) noexcept;

    // Pointer ...
    struct pointer__allocate_heap_memory;
    struct pointer__allocate_stack_memory;
    template <typename type> void pointer__free_heap_memory(type* const) noexcept;
    template <typename type> constexpr void pointer__free_stack_memory(type* const) noexcept;
    struct pointer__map_heap_memory;
    struct pointer__reallocate_heap_memory;
    struct pointer__reallocate_stack_memory;
    template <typename type> void pointer__source_copy_memory(type* const, type* const, size_t const) noexcept;
    template <typename type> void pointer__source_move_memory(type* const, type* const, size_t const) noexcept;
    template <typename type> void pointer__unmap_heap_memory(type* const, size_t const) noexcept;
    template <typename type> void pointer__zero_memory(type* const, size_t const) noexcept;

    // String ... --- CHECKPOINT (Lapys)
    constexpr inline char* string__end(char*) noexcept;
    constexpr inline char const* string__end(char const*) noexcept;
    template <size_t length> constexpr inline char* string__end(char (&)[length]) noexcept;
    template <size_t length> constexpr inline char const* string__end(char const (&)[length]) noexcept;
    constexpr inline char8_t* string__end(char8_t*) noexcept;
    constexpr inline char8_t const* string__end(char8_t const*) noexcept;
    template <size_t length> constexpr inline char8_t* string__end(char8_t (&)[length]) noexcept;
    template <size_t length> constexpr inline char8_t const* string__end(char8_t const (&)[length]) noexcept;
    constexpr inline char16_t* string__end(char16_t*) noexcept;
    constexpr inline char16_t const* string__end(char16_t const*) noexcept;
    template <size_t length> constexpr inline char16_t* string__end(char16_t (&)[length]) noexcept;
    template <size_t length> constexpr inline char16_t const* string__end(char16_t const (&)[length]) noexcept;
    constexpr inline char32_t* string__end(char32_t*) noexcept;
    constexpr inline char32_t const* string__end(char32_t const*) noexcept;
    template <size_t length> constexpr inline char32_t* string__end(char32_t (&)[length]) noexcept;
    template <size_t length> constexpr inline char32_t const* string__end(char32_t const (&)[length]) noexcept;
    constexpr inline wchar_t* string__end(wchar_t*) noexcept;
    constexpr inline wchar_t const* string__end(wchar_t const*) noexcept;
    template <size_t length> constexpr inline wchar_t* string__end(wchar_t (&)[length]) noexcept;
    template <size_t length> constexpr inline wchar_t const* string__end(wchar_t const (&)[length]) noexcept;

    bool string__is_empty(char* const) noexcept;
    bool string__is_empty(char const* const) noexcept;
    bool string__is_empty(char8_t* const) noexcept;
    bool string__is_empty(char8_t const* const) noexcept;
    bool string__is_empty(char16_t* const) noexcept;
    bool string__is_empty(char16_t const* const) noexcept;
    bool string__is_empty(char32_t* const) noexcept;
    bool string__is_empty(char32_t const* const) noexcept;
    bool string__is_empty(wchar_t* const) noexcept;
    bool string__is_empty(wchar_t const* const) noexcept;

    constexpr size_t string__length(char* const) noexcept;
    constexpr size_t string__length(char const* const) noexcept;
    template <size_t length> size_t string__length(char (&)[length]) noexcept;
    template <size_t length> size_t string__length(char const (&)[length]) noexcept;
    size_t string__length(char8_t* const) noexcept;
    size_t string__length(char8_t const* const) noexcept;
    template <size_t length> size_t string__length(char8_t (&)[length]) noexcept;
    template <size_t length> size_t string__length(char8_t const (&)[length]) noexcept;
    size_t string__length(char16_t* const) noexcept;
    size_t string__length(char16_t const* const) noexcept;
    template <size_t length> size_t string__length(char16_t (&)[length]) noexcept;
    template <size_t length> size_t string__length(char16_t const (&)[length]) noexcept;
    size_t string__length(char32_t* const) noexcept;
    size_t string__length(char32_t const* const) noexcept;
    template <size_t length> size_t string__length(char32_t (&)[length]) noexcept;
    template <size_t length> size_t string__length(char32_t const (&)[length]) noexcept;
    constexpr size_t string__length(wchar_t* const) noexcept;
    constexpr size_t string__length(wchar_t const* const) noexcept;
    template <size_t length> size_t string__length(wchar_t (&)[length]) noexcept;
    template <size_t length> size_t string__length(wchar_t const (&)[length]) noexcept;

/* Import */
#include "general.cpp" // NOTE (Lapys) -> Define all data interfaces.
#include "shims/primitives.cpp" // NOTE (Lapys) -> Modified self-managed atomic types.
#include "shims/types.cpp" // NOTE (Lapys) -> Modified type interfaces.

#include "shims/definitions.hpp" // NOTE (Lapys) -> Atomic/ minimal development code features and re-definitions.
#include "shims/constants.hpp" // NOTE (Lapys) -> Global utility constants and objects.

/* Main */
void Main(Arguments const);

#if environment__is_linux
int main(int const /*argumentCount*/, char* const /*argumentVector*/[]) {
    // Return
    return EXIT_SUCCESS;
}

#elif environment__is_windows // CHECKPOINT (Lapys) -> Get the directory of the executing script and de-allocate each argument string.
int WinMain(HINSTANCE const /*instanceHandle*/, HINSTANCE const /*previousInstanceHandle*/, LPSTR const /*programInitiationCommandLineArguments*/, int const/*windowAppearance*/) {
    // Return
    return EXIT_SUCCESS;
}

#else
int main(void) {
    // Return
    return EXIT_SUCCESS;
}

#endif
